version: "2.3"
services:
  mysql:
    container_name: db_messaging
    image: mysql:5.7
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d/
    ports:
      - 33061:3306
    expose:
      - '3306'
    environment:
      - MYSQL_DATABASE=db_message
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123
      - MYSQL_ROOT_PASSWORD=123
    networks: 
      - net
  serverjs:
    build: ./
    command: npm start
    networks: 
      - net
    ports:
      - 3000:3000
      - 3333:3333
    expose:
      - '3000'
networks: 
  net:
    driver: bridge